appname: wavecafe
deploymentname: wavecafe
#deploymentname:$deploymentname  [Note: When referring to values from a variable group, use $ followed by the variable name or specify the variable's calling within the file.]
servicename: wave-cafe

image:
  name: saitejairrinki/wavecafe
  tag: v1

hpa:
  name: wavecafe-hpa
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 50



